### ISSUE TITLE
error while running make

### ISSUE THREAD

**Issue by sasuseso** [PFLab-OS/Toshokan#41]
I got an error while running make in Toshokan/tutorial/paging/mapping.
error message:
Silent mode is enabled by default. You can turn it off with make V=1'.
\>>> clean up old environments
\>>> start a QEMU container
make: *** [Makefile:69: prepare_remote] エラー 125

OS: Arch Linux

**Comment by liva** [comment]
Thanks for the issue.
Could you please run it again with `make V=1` and attach the output?
It would make it easier to clarify the problem.

**Comment by sasuseso** [comment]
docker rm -f toshokan_qemu > /dev/null 2>&1 || :
docker run -d --name toshokan_qemu -v /home/sinai/Scripts/Toshokan/tutorial/paging/mapping:/home/sinai/Scripts/Toshokan/tutorial/paging/mapping -w /home/sinai/Scripts/Toshokan/tutorial/paging/mapping livadk/toshokan_qemu:v0.04b qemu-system-x86_64 -cpu Haswell -s -d cpu_reset -no-reboot -smp 5 -m 4G -D /qemu.log -loadvm snapshot1 -hda /backing.qcow2 -net nic -net user,hostfwd=tcp::2222-:22 -serial telnet::4444,server,nowait -monitor telnet::4445,server,nowait -nographic -global hpet.msi=true > /dev/null 2>&1
make: *** [Makefile:69: prepare_remote] エラー 125

**Comment by liva** [comment]
I got it! I forgot to upload the new version of docker image. (livadk/toshokan_qemu:v0.04b)
I've already fixed it, so it should work fine now.

**Comment by sasuseso** [comment]
Thank you so much!

**Comment by liva** [comment]
Thanks for your contribution to this project!
