### ISSUE TITLE
error while running make

### ISSUE THREAD

**Issue by sasuseso** [PFLab-OS/Toshokan#42]
I'm sorry for frequently issue.
I got an error while running "make monitor".

error message(make monitor V=1):
docker exec toshokan_qemu sh -c "echo 'cpu 1' | nc localhost 4445 > /dev/zero"
Error: No such container: toshokan_qemu
make: *** [Makefile:83: monitor] エラー 1

**Comment by sasuseso** [comment]
I'm sorry it fixed.

**Comment by liva** [comment]
No problem!
Well, I want to know the cause of this trouble.
Maybe we can make Toshokan more user-friendly (for example, showing some instructions in outputs), and it would save other people's time.

**Comment by sasuseso** [comment]
Thank you. m(_ _)m

**Comment by liva** [comment]
I mean, how did you fix this? :)

**Comment by sasuseso** [comment]
Sorry, I don't know what happened I tried after while and then it fixed.
What should I do to know what happend?
Could you help me?

**Comment by liva** [comment]
Hmm.. You mean, you can't reproduce this problem anymore, right?
Well, it's OK then. I'll leave it until another guy mention it.

Thanks for your cooperation!

**Comment by sasuseso** [comment]
I'm sorry for I could not help you.
